name: Master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Update code
      - uses: actions/checkout@v2
      
      # Setup env
      - name: JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build a runnable jar
      - name: Shadow Jar
        run: ./gradlew shadowJar

      - uses: actions/checkout@v1
      - uses:  ncipollo/release-action@v1
      - name: Publish to Release
        with:
          artifacts: ./build/libs/HomeEntity-1.0-SNAPSHOT-all.jar
          bodyFile: ./release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
